---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Virtualization:
    - Proxmox:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/proxmox.webp
        href: https://10.0.0.95:8006
        description: PVE1
    - PBS:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/proxmox-light.webp
        href: https://10.0.0.93:8007
        description: Proxmox Backup Server
    - TrueNAS:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/truenas.webp
        href: https://truenas-scale.tuxedo-wahoo.ts.net/ui/sessions/signin
        description: TrueNAS Scale Electric Eel

- Services:
    - Immich:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/immich.webp
        href: http://10.0.0.92:30041
        description: Immich Photo and Video Library
        widget:
            type: immich
            url: http://10.0.0.92:30041
            key: VgX6MksfH9wZ5W4EOILq9lzqBrDkCr1CgwPW3pmY
            version: 2
    - Dockge:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/dockge.webp
        href: http://10.0.0.99:5001
        description: Dockge Dashboard
    - Home Assistant:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/home-assistant.webp
        href: http://homeassistant.local:8123/lovelace/0
        description: Home Assistant Dashboard
    - Jellyfin:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/jellyfin.webp
        href: http://10.0.0.92:30013
        description: Jellyfin Media Server
    - Beszel:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/beszel.webp
        href: http://10.0.0.99:8090
        description: Beszel Server Monitoring
    - PgAdmin:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/pgadmin.webp
        href: http://10.0.0.99:5050/browser/
        description: PgAdmin Postgres Dashboard
    - Redis Insight:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/redis.webp
        href: http://10.0.0.99:8001/redis-stack/browser
        description: Redis Insight Dashboard
    - Open WebUI:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/open-webui.webp
        href: http://10.0.0.92:31028
        description: Open WebUI Dashboard
    - Wallos:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/wallos.webp
        href: http://10.0.0.99:8282/
        description: Wallos Subscription Manager
    - Maybe Finance:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/maybe.webp
        href: http://10.0.0.99:3001
        description: Maybe Finance Dashboard
    

- Network:
    - Unifi Controller:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/unifi.webp
        href: https://unifi.tuxedo-wahoo.ts.net:8443/manage/account/login?redirect=/manage
        description: Unifi Network
    - Adguard Home 1:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/adguard-home.webp
        href: https://10.0.0.39:8083
        description: Adguard Home Diet Pi
    - Adguard Home 2:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/adguard-home.webp
        href: https://10.0.0.210
        description: Adguard Home Proxmox
    - Traefik:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/traefik.webp
        href: http://10.0.0.161:8080
        description: Traefik Proxy
