---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

# - resources:
#     cpu: true
#     memory: true
#     disk: /

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short

- openmeteo:
    label: Reno # optional
    latitude: 39.5296
    longitude: -119.8138
    timezone: America/Los_Angeles # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
