services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: unless-stopped
networks: {}
