services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - 8282:80/tcp
    environment:
      TZ: America/Los_Angeles
    # Volumes store your data between container upgrades
    volumes:
      - /data/wallos/db:/var/www/html/db
      - /data/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
