services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    volumes:
      - /data/redis-stack/:/data
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    networks:
      - store
volumes:
  redis-stack: null
networks:
  store:
    external: true
